version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      tooling:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/studio"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      studio:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
