import { defineArrayMember, defineField, defineType } from "sanity";

export const therapistType = defineType({
  name: "therapist",
  title: "Therapist",
  type: "document",
  groups: [
    { name: "profile", title: "Profile", default: true },
    { name: "practice", title: "Practice" },
    { name: "trust", title: "Trust & Fit" },
    { name: "directory", title: "Directory" },
    { name: "billing", title: "Billing" },
  ],
  fields: [
    defineField({
      name: "name",
      title: "Full name",
      type: "string",
      group: "profile",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      group: "profile",
      options: {
        source: (doc: any) => [doc.name, doc.city, doc.state].filter(Boolean).join(" "),
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "credentials",
      title: "Credentials",
      type: "string",
      group: "profile",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "title",
      title: "Professional title",
      type: "string",
      group: "profile",
    }),
    defineField({
      name: "photo",
      title: "Photo",
      type: "image",
      group: "profile",
      options: {
        hotspot: true,
      },
    }),
    defineField({
      name: "bio",
      title: "Full bio",
      type: "text",
      rows: 6,
      group: "profile",
      validation: (rule) => rule.required().min(50),
    }),
    defineField({
      name: "bioPreview",
      title: "Directory bio preview",
      type: "text",
      rows: 3,
      group: "directory",
      description: "Optional shorter summary for cards. If left blank, the full bio will be used.",
    }),
    defineField({
      name: "practiceName",
      title: "Practice name",
      type: "string",
      group: "practice",
    }),
    defineField({
      name: "email",
      title: "Public email",
      type: "string",
      group: "practice",
    }),
    defineField({
      name: "phone",
      title: "Public phone",
      type: "string",
      group: "practice",
    }),
    defineField({
      name: "website",
      title: "Website",
      type: "url",
      group: "practice",
    }),
    defineField({
      name: "preferredContactMethod",
      title: "Preferred contact method",
      type: "string",
      group: "practice",
      options: {
        list: [
          { title: "Email", value: "email" },
          { title: "Phone", value: "phone" },
          { title: "Website", value: "website" },
          { title: "Booking link", value: "booking" },
        ],
      },
    }),
    defineField({
      name: "preferredContactLabel",
      title: "Primary contact CTA label",
      type: "string",
      group: "practice",
      description: "Optional button label shown to users, such as 'Book a consultation'.",
    }),
    defineField({
      name: "contactGuidance",
      title: "Contact guidance",
      type: "text",
      rows: 3,
      group: "practice",
      description: "Short note to help users know what to include or expect when they reach out.",
    }),
    defineField({
      name: "firstStepExpectation",
      title: "What happens after outreach",
      type: "text",
      rows: 3,
      group: "practice",
      description:
        "Describe the first step after someone reaches out, such as a consult call or intake review.",
    }),
    defineField({
      name: "bookingUrl",
      title: "Booking URL",
      type: "url",
      group: "practice",
    }),
    defineField({
      name: "city",
      title: "City",
      type: "string",
      group: "practice",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "state",
      title: "State",
      type: "string",
      group: "practice",
      validation: (rule) => rule.required().length(2),
    }),
    defineField({
      name: "zip",
      title: "ZIP code",
      type: "string",
      group: "practice",
    }),
    defineField({
      name: "country",
      title: "Country",
      type: "string",
      group: "practice",
      initialValue: "US",
    }),
    defineField({
      name: "licenseState",
      title: "License state",
      type: "string",
      group: "trust",
    }),
    defineField({
      name: "licenseNumber",
      title: "License number",
      type: "string",
      group: "trust",
    }),
    defineField({
      name: "careApproach",
      title: "How they help bipolar clients",
      type: "text",
      rows: 4,
      group: "trust",
    }),
    defineField({
      name: "treatmentModalities",
      title: "Treatment modalities",
      type: "array",
      group: "trust",
      of: [defineArrayMember({ type: "string" })],
      options: {
        layout: "tags",
      },
    }),
    defineField({
      name: "clientPopulations",
      title: "Populations served",
      type: "array",
      group: "trust",
      of: [defineArrayMember({ type: "string" })],
      options: {
        layout: "tags",
      },
    }),
    defineField({
      name: "specialties",
      title: "Specialties",
      type: "array",
      group: "directory",
      of: [defineArrayMember({ type: "string" })],
      options: {
        layout: "tags",
      },
    }),
    defineField({
      name: "insuranceAccepted",
      title: "Insurance accepted",
      type: "array",
      group: "directory",
      of: [defineArrayMember({ type: "string" })],
      options: {
        layout: "tags",
      },
    }),
    defineField({
      name: "languages",
      title: "Languages",
      type: "array",
      group: "directory",
      of: [defineArrayMember({ type: "string" })],
      options: {
        layout: "tags",
      },
      initialValue: ["English"],
    }),
    defineField({
      name: "yearsExperience",
      title: "Years of experience",
      type: "number",
      group: "directory",
    }),
    defineField({
      name: "bipolarYearsExperience",
      title: "Years treating bipolar disorder",
      type: "number",
      group: "trust",
    }),
    defineField({
      name: "acceptsTelehealth",
      title: "Offers telehealth",
      type: "boolean",
      group: "directory",
      initialValue: true,
    }),
    defineField({
      name: "acceptsInPerson",
      title: "Offers in-person sessions",
      type: "boolean",
      group: "directory",
      initialValue: true,
    }),
    defineField({
      name: "acceptingNewPatients",
      title: "Accepting new patients",
      type: "boolean",
      group: "directory",
      initialValue: true,
    }),
    defineField({
      name: "telehealthStates",
      title: "Telehealth states",
      type: "array",
      group: "trust",
      of: [defineArrayMember({ type: "string" })],
      options: {
        layout: "tags",
      },
    }),
    defineField({
      name: "estimatedWaitTime",
      title: "Estimated wait time",
      type: "string",
      group: "trust",
    }),
    defineField({
      name: "medicationManagement",
      title: "Provides medication management",
      type: "boolean",
      group: "trust",
      initialValue: false,
    }),
    defineField({
      name: "verificationStatus",
      title: "Verification status",
      type: "string",
      group: "trust",
      options: {
        list: [
          { title: "Under review", value: "under_review" },
          { title: "Editorially verified", value: "editorially_verified" },
        ],
      },
      initialValue: "editorially_verified",
    }),
    defineField({
      name: "sessionFeeMin",
      title: "Minimum session fee",
      type: "number",
      group: "billing",
    }),
    defineField({
      name: "sessionFeeMax",
      title: "Maximum session fee",
      type: "number",
      group: "billing",
    }),
    defineField({
      name: "slidingScale",
      title: "Sliding scale available",
      type: "boolean",
      group: "billing",
      initialValue: false,
    }),
    defineField({
      name: "listingActive",
      title: "Listing active",
      type: "boolean",
      group: "directory",
      initialValue: true,
      description: "Turn this off to hide the listing without deleting it.",
    }),
    defineField({
      name: "status",
      title: "Status",
      type: "string",
      group: "directory",
      options: {
        list: [
          { title: "Active", value: "active" },
          { title: "Draft", value: "draft" },
          { title: "Archived", value: "archived" },
        ],
      },
      initialValue: "active",
    }),
  ],
  preview: {
    select: {
      title: "name",
      subtitle: "city",
      state: "state",
      media: "photo",
    },
    prepare: (selection) => ({
      title: selection.title,
      subtitle: [selection.subtitle, selection.state].filter(Boolean).join(", "),
      media: selection.media,
    }),
  },
});
