import { defineArrayMember, defineField, defineType } from "sanity";

export const therapistCandidateType = defineType({
  name: "therapistCandidate",
  title: "Therapist Candidate",
  type: "document",
  groups: [
    { name: "identity", title: "Identity", default: true },
    { name: "source", title: "Source & Extraction" },
    { name: "fit", title: "Fit & Coverage" },
    { name: "review", title: "Review & Dedupe" },
  ],
  fields: [
    defineField({
      name: "candidateId",
      title: "Candidate ID",
      type: "string",
      group: "identity",
      validation: (rule) => rule.required(),
      description: "Stable candidate identifier from the sourcing pipeline.",
    }),
    defineField({
      name: "providerFingerprint",
      title: "Provider fingerprint",
      type: "string",
      group: "identity",
      description: "Normalized identity fingerprint used for dedupe and merge decisions.",
    }),
    defineField({
      name: "providerId",
      title: "Provider ID",
      type: "string",
      group: "identity",
      description: "Canonical therapist identity key once the candidate resolves to a real provider entity.",
    }),
    defineField({
      name: "name",
      title: "Full name",
      type: "string",
      group: "identity",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "credentials",
      title: "Credentials",
      type: "string",
      group: "identity",
    }),
    defineField({
      name: "title",
      title: "Professional title",
      type: "string",
      group: "identity",
    }),
    defineField({
      name: "practiceName",
      title: "Practice name",
      type: "string",
      group: "identity",
    }),
    defineField({
      name: "city",
      title: "City",
      type: "string",
      group: "identity",
    }),
    defineField({
      name: "state",
      title: "State",
      type: "string",
      group: "identity",
    }),
    defineField({
      name: "zip",
      title: "ZIP code",
      type: "string",
      group: "identity",
    }),
    defineField({
      name: "country",
      title: "Country",
      type: "string",
      group: "identity",
      initialValue: "US",
    }),
    defineField({
      name: "licenseState",
      title: "License state",
      type: "string",
      group: "identity",
    }),
    defineField({
      name: "licenseNumber",
      title: "License number",
      type: "string",
      group: "identity",
    }),
    defineField({
      name: "email",
      title: "Public email",
      type: "string",
      group: "identity",
    }),
    defineField({
      name: "phone",
      title: "Public phone",
      type: "string",
      group: "identity",
    }),
    defineField({
      name: "website",
      title: "Website",
      type: "url",
      group: "identity",
    }),
    defineField({
      name: "bookingUrl",
      title: "Booking URL",
      type: "url",
      group: "identity",
    }),
    defineField({
      name: "sourceType",
      title: "Source type",
      type: "string",
      group: "source",
      options: {
        list: [
          { title: "Practice website", value: "practice_website" },
          { title: "Directory profile", value: "directory_profile" },
          { title: "Licensing board", value: "licensing_board" },
          { title: "Therapist-submitted", value: "therapist_submitted" },
          { title: "Manual research", value: "manual_research" },
          { title: "Imported batch", value: "import_batch" },
        ],
      },
    }),
    defineField({
      name: "sourceUrl",
      title: "Primary source URL",
      type: "url",
      group: "source",
    }),
    defineField({
      name: "supportingSourceUrls",
      title: "Supporting source URLs",
      type: "array",
      group: "source",
      of: [defineArrayMember({ type: "url" })],
    }),
    defineField({
      name: "rawSourceSnapshot",
      title: "Raw source snapshot",
      type: "text",
      rows: 8,
      group: "source",
      description: "Plain-text snapshot or structured source notes retained for auditability.",
    }),
    defineField({
      name: "extractedAt",
      title: "Extracted at",
      type: "datetime",
      group: "source",
    }),
    defineField({
      name: "sourceReviewedAt",
      title: "Source reviewed at",
      type: "datetime",
      group: "source",
    }),
    defineField({
      name: "extractionVersion",
      title: "Extraction version",
      type: "string",
      group: "source",
    }),
    defineField({
      name: "extractionConfidence",
      title: "Extraction confidence",
      type: "number",
      group: "source",
      validation: (rule) => rule.min(0).max(1),
      description: "0-1 confidence score for the extracted record.",
    }),
    defineField({
      name: "careApproach",
      title: "How they help bipolar clients",
      type: "text",
      rows: 4,
      group: "fit",
    }),
    defineField({
      name: "specialties",
      title: "Specialties",
      type: "array",
      group: "fit",
      of: [defineArrayMember({ type: "string" })],
      options: {
        layout: "tags",
      },
    }),
    defineField({
      name: "treatmentModalities",
      title: "Treatment modalities",
      type: "array",
      group: "fit",
      of: [defineArrayMember({ type: "string" })],
      options: {
        layout: "tags",
      },
    }),
    defineField({
      name: "clientPopulations",
      title: "Populations served",
      type: "array",
      group: "fit",
      of: [defineArrayMember({ type: "string" })],
      options: {
        layout: "tags",
      },
    }),
    defineField({
      name: "insuranceAccepted",
      title: "Insurance accepted",
      type: "array",
      group: "fit",
      of: [defineArrayMember({ type: "string" })],
      options: {
        layout: "tags",
      },
    }),
    defineField({
      name: "languages",
      title: "Languages",
      type: "array",
      group: "fit",
      of: [defineArrayMember({ type: "string" })],
      options: {
        layout: "tags",
      },
    }),
    defineField({
      name: "acceptsTelehealth",
      title: "Offers telehealth",
      type: "boolean",
      group: "fit",
      initialValue: true,
    }),
    defineField({
      name: "acceptsInPerson",
      title: "Offers in-person sessions",
      type: "boolean",
      group: "fit",
      initialValue: true,
    }),
    defineField({
      name: "acceptingNewPatients",
      title: "Accepting new patients",
      type: "boolean",
      group: "fit",
    }),
    defineField({
      name: "telehealthStates",
      title: "Telehealth states",
      type: "array",
      group: "fit",
      of: [defineArrayMember({ type: "string" })],
      options: {
        layout: "tags",
      },
    }),
    defineField({
      name: "estimatedWaitTime",
      title: "Estimated wait time",
      type: "string",
      group: "fit",
    }),
    defineField({
      name: "medicationManagement",
      title: "Provides medication management",
      type: "boolean",
      group: "fit",
    }),
    defineField({
      name: "sessionFeeMin",
      title: "Minimum session fee",
      type: "number",
      group: "fit",
    }),
    defineField({
      name: "sessionFeeMax",
      title: "Maximum session fee",
      type: "number",
      group: "fit",
    }),
    defineField({
      name: "slidingScale",
      title: "Sliding scale available",
      type: "boolean",
      group: "fit",
      initialValue: false,
    }),
    defineField({
      name: "dedupeStatus",
      title: "Dedupe status",
      type: "string",
      group: "review",
      options: {
        list: [
          { title: "Unreviewed", value: "unreviewed" },
          { title: "Unique", value: "unique" },
          { title: "Possible duplicate", value: "possible_duplicate" },
          { title: "Merged", value: "merged" },
          { title: "Rejected duplicate", value: "rejected_duplicate" },
        ],
      },
      initialValue: "unreviewed",
    }),
    defineField({
      name: "dedupeConfidence",
      title: "Dedupe confidence",
      type: "number",
      group: "review",
      validation: (rule) => rule.min(0).max(1),
    }),
    defineField({
      name: "matchedTherapistSlug",
      title: "Matched therapist slug",
      type: "string",
      group: "review",
    }),
    defineField({
      name: "matchedTherapistId",
      title: "Matched therapist ID",
      type: "string",
      group: "review",
    }),
    defineField({
      name: "matchedApplicationId",
      title: "Matched application ID",
      type: "string",
      group: "review",
    }),
    defineField({
      name: "reviewStatus",
      title: "Review status",
      type: "string",
      group: "review",
      options: {
        list: [
          { title: "Queued", value: "queued" },
          { title: "Needs review", value: "needs_review" },
          { title: "Needs confirmation", value: "needs_confirmation" },
          { title: "Ready to publish", value: "ready_to_publish" },
          { title: "Published", value: "published" },
          { title: "Archived", value: "archived" },
        ],
      },
      initialValue: "queued",
    }),
    defineField({
      name: "readinessScore",
      title: "Readiness score",
      type: "number",
      group: "review",
      validation: (rule) => rule.min(0).max(100),
    }),
    defineField({
      name: "publishRecommendation",
      title: "Publish recommendation",
      type: "string",
      group: "review",
      options: {
        list: [
          { title: "Ready", value: "ready" },
          { title: "Needs confirmation", value: "needs_confirmation" },
          { title: "Hold", value: "hold" },
          { title: "Reject", value: "reject" },
        ],
      },
    }),
    defineField({
      name: "notes",
      title: "Internal notes",
      type: "text",
      rows: 5,
      group: "review",
    }),
  ],
  preview: {
    select: {
      title: "name",
      city: "city",
      state: "state",
      reviewStatus: "reviewStatus",
      dedupeStatus: "dedupeStatus",
    },
    prepare(selection) {
      const subtitle = [
        [selection.city, selection.state].filter(Boolean).join(", "),
        selection.reviewStatus,
        selection.dedupeStatus,
      ]
        .filter(Boolean)
        .join(" · ");

      return {
        title: selection.title || "Unnamed candidate",
        subtitle,
      };
    },
  },
});
