// Seeded therapist fixtures for the hermetic E2E suite. Shaped like real
// Sanity therapist documents (camelCase fields, _type "therapist") so the
// in-memory client and the public-content projections both read them the
// way they read production data. All four are CA, published, and listed
// (listingActive true, status "active", visibilityIntent "listed",
// licenseNumber present) — the directory and match flows should surface
// every one of them; filters and ranking differentiate from there.

function buildTherapist(overrides) {
  const base = {
    _type: "therapist",
    country: "US",
    state: "CA",
    licenseState: "CA",
    lifecycle: "approved",
    listingActive: true,
    status: "active",
    visibilityIntent: "listed",
    acceptingNewPatients: true,
    claimStatus: "unclaimed",
    verificationStatus: "editorially_verified",
    sourceReviewedAt: "2026-05-01T00:00:00.000Z",
    languages: ["English"],
    clientPopulations: ["Adults"],
    therapistReportedFields: [],
    fieldReviewStates: {},
    licensureVerification: {
      verifiedAt: "2026-05-01T00:00:00.000Z",
      statusStanding: "current",
      primaryStatus: "active",
    },
  };
  return { ...base, ...overrides };
}

export const E2E_THERAPISTS = [
  buildTherapist({
    _id: "therapist-e2e-maya-hernandez",
    name: "Maya Hernandez",
    credentials: "LMFT",
    title: "Therapist",
    slug: { _type: "slug", current: "maya-hernandez-lmft" },
    email: "maya@example.test",
    preferredContactMethod: "email",
    city: "San Francisco",
    zip: "94110",
    licenseNumber: "LMFT104210",
    bio: "Bipolar-focused therapist helping adults build stable routines after a new diagnosis.",
    bioPreview: "Bipolar-focused therapist helping adults build stable routines.",
    careApproach: "Collaborative, structured, relapse-prevention oriented.",
    specialties: ["Bipolar disorder", "Bipolar II", "IPSRT"],
    treatmentModalities: ["IPSRT", "CBT"],
    insuranceAccepted: ["Aetna", "Blue Shield of California"],
    acceptsTelehealth: true,
    acceptsInPerson: false,
    telehealthStates: ["CA"],
    yearsExperience: 12,
    bipolarYearsExperience: 9,
    medicationManagement: false,
    sessionFeeMin: 150,
    sessionFeeMax: 200,
    slidingScale: true,
    gender: "female",
    estimatedWaitTime: "Within a week",
  }),
  buildTherapist({
    _id: "therapist-e2e-daniel-okafor",
    name: "Daniel Okafor",
    credentials: "PsyD",
    title: "Psychologist",
    slug: { _type: "slug", current: "daniel-okafor-psyd" },
    email: "daniel@example.test",
    preferredContactMethod: "email",
    city: "Los Angeles",
    zip: "90025",
    licenseNumber: "PSY31988",
    bio: "Psychologist specializing in bipolar I with co-occurring anxiety.",
    bioPreview: "Psychologist specializing in bipolar I with co-occurring anxiety.",
    careApproach: "Evidence-based, family-inclusive.",
    specialties: ["Bipolar disorder", "Bipolar I", "FFT"],
    treatmentModalities: ["FFT", "DBT"],
    insuranceAccepted: ["Kaiser Permanente"],
    acceptsTelehealth: true,
    acceptsInPerson: true,
    telehealthStates: ["CA"],
    yearsExperience: 15,
    bipolarYearsExperience: 11,
    medicationManagement: false,
    sessionFeeMin: 180,
    sessionFeeMax: 240,
    slidingScale: false,
    gender: "male",
    estimatedWaitTime: "1-2 weeks",
  }),
  buildTherapist({
    _id: "therapist-e2e-priya-natarajan",
    name: "Priya Natarajan",
    credentials: "MD",
    title: "Psychiatrist",
    slug: { _type: "slug", current: "priya-natarajan-md" },
    email: "priya@example.test",
    preferredContactMethod: "email",
    city: "Oakland",
    zip: "94607",
    licenseNumber: "A123456",
    bio: "Psychiatrist offering medication management for bipolar spectrum disorders.",
    bioPreview: "Psychiatrist offering medication management for bipolar spectrum disorders.",
    careApproach: "Measurement-based medication management with psychotherapy referrals.",
    specialties: ["Bipolar disorder", "Mixed features", "Medication management"],
    treatmentModalities: ["Psychopharmacology"],
    insuranceAccepted: ["Aetna", "Cigna"],
    acceptsTelehealth: true,
    acceptsInPerson: true,
    telehealthStates: ["CA"],
    yearsExperience: 18,
    bipolarYearsExperience: 14,
    medicationManagement: true,
    sessionFeeMin: 250,
    sessionFeeMax: 350,
    slidingScale: false,
    gender: "female",
    estimatedWaitTime: "Within a week",
  }),
  buildTherapist({
    _id: "therapist-e2e-grace-lin",
    name: "Grace Lin",
    credentials: "LCSW",
    title: "Therapist",
    slug: { _type: "slug", current: "grace-lin-lcsw" },
    email: "grace@example.test",
    preferredContactMethod: "email",
    city: "San Diego",
    zip: "92103",
    licenseNumber: "LCSW88412",
    bio: "In-person bipolar and mood disorder therapy in San Diego.",
    bioPreview: "In-person bipolar and mood disorder therapy in San Diego.",
    careApproach: "Warm, skills-first, DBT-informed.",
    specialties: ["Bipolar disorder", "Cyclothymia", "DBT"],
    treatmentModalities: ["DBT", "Mindfulness"],
    insuranceAccepted: [],
    acceptsTelehealth: false,
    acceptsInPerson: true,
    telehealthStates: [],
    yearsExperience: 8,
    bipolarYearsExperience: 6,
    medicationManagement: false,
    sessionFeeMin: 130,
    sessionFeeMax: 170,
    slidingScale: true,
    gender: "female",
    estimatedWaitTime: "1-2 weeks",
  }),
];

export const E2E_THERAPIST_NAMES = E2E_THERAPISTS.map(function (doc) {
  return doc.name;
});
